name: Action demo
on: push
jobs:
  action:
    runs-on: ubuntu-slim
    steps:
      - name: checkout the code
        uses: action/checkout@v4
      - name: print index.html file
        run: cat index.html

  

        

